Repository 0Nom4D/ToysRevive, pull requests merged in 2023-11, with the labels that each got.

#6 Server: Setup
  .github/actions/install-stack/action.yml
  .github/workflows/server.yaml
  .gitignore
  server/.gitignore
  server/.hlint.yaml
  server/LICENSE
  server/README.md
  server/Setup.hs
  server/ToysRevive-server.cabal
  server/app/Main.hs
  server/codecov.json
  server/fourmolu.yaml
  server/package.yaml
  server/robot/helloworld/helloworld.robot
  server/robot/requirements.txt
  server/robot/rest.resource
  server/src/API/ServerMessage.hs
  server/src/Server.hs
  server/stack.yaml
  server/stack.yaml.lock
  server/test/Spec.hs
  server/test/TestServer.hs
Labels: DevOps, Back

#7 Jetpack Compose Lint, Build & Test CI
  .github/workflows/jetpack_compose.yaml
  .gitignore
  mobile/.gradle/8.0/checksums/checksums.lock
  mobile/.gradle/8.0/checksums/md5-checksums.bin
  mobile/.gradle/8.0/checksums/sha1-checksums.bin
  mobile/.gradle/8.0/dependencies-accessors/dependencies-accessors.lock
  mobile/.gradle/8.0/dependencies-accessors/gc.properties
  mobile/.gradle/8.0/executionHistory/executionHistory.bin
  mobile/.gradle/8.0/executionHistory/executionHistory.lock
  mobile/.gradle/8.0/fileChanges/last-build.bin
  mobile/.gradle/8.0/fileHashes/fileHashes.bin
  mobile/.gradle/8.0/fileHashes/fileHashes.lock
  mobile/.gradle/8.0/fileHashes/resourceHashesCache.bin
  mobile/.gradle/8.0/gc.properties
  mobile/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  mobile/.gradle/buildOutputCleanup/cache.properties
  mobile/.gradle/buildOutputCleanup/outputFiles.bin
  mobile/.gradle/file-system.probe
  mobile/.gradle/vcs-1/gc.properties
  mobile/build.gradle.kts
  mobile/detekt.yml
  mobile/gradle/wrapper/gradle-wrapper.jar
  mobile/local.properties
Labels: Build, DevOps, Test Policy

#9 Fixing security error on Gradle Action
  .github/workflows/jetpack_compose.yaml
Labels: DevOps
