Repository 0Nom4D/ToysRevive, pull requests merged in 2024-02, with the labels that each got.

#19 Server: Liked, Disliked and New Listings
  server/prisma/migrations/20240206133135_likes/migration.sql
  server/prisma/schema.prisma
  server/src/authentication/local/local.strategy.ts
  server/src/toy-listing/toy-listing.controller.spec.ts
  server/src/toy-listing/toy-listing.controller.ts
  server/src/toy-listing/toy-listing.service.ts
  server/src/user/user.controller.spec.ts
Labels: Back

#23 Mobile: Authentification (Login / Register)
  README.md
  mobile/app/build.gradle.kts
  mobile/app/src/main/java/nom4d/toysrevive/MainActivity.kt
  mobile/app/src/main/java/nom4d/toysrevive/api/dtos/RegisterDto.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/AuthNavigationHost.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/LoginView.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/LoginViewModel.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/RegisterView.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/RegisterViewModel.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/steps/IdsStep.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/steps/NameStep.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/steps/PasswordStep.kt
  mobile/app/src/main/java/nom4d/toysrevive/auth/steps/PhoneStep.kt
  mobile/app/src/main/java/nom4d/toysrevive/biometrics/BiometricPrompt.kt
  mobile/app/src/main/java/nom4d/toysrevive/ext/GetActivity.kt
  mobile/app/src/main/java/nom4d/toysrevive/home/HomeScreen.kt
  mobile/app/src/main/java/nom4d/toysrevive/navigation/MainNavigationHost.kt
  mobile/app/src/main/java/nom4d/toysrevive/navigation/NavigationItem.kt
  mobile/app/src/main/java/nom4d/toysrevive/validators/Validators.kt
  server/prisma/migrations/20240206133135_likes/migration.sql
  server/prisma/schema.prisma
  server/src/authentication/local/local.strategy.ts
  server/src/toy-listing/toy-listing.controller.spec.ts
  server/src/toy-listing/toy-listing.controller.ts
  server/src/toy-listing/toy-listing.service.ts
  server/src/user/user.controller.spec.ts
Labels: Enhancement, Front, Build, Dependencies, Mobile

#24 Server: Fix Dockerisation for prod
  .env.example
  server/Dockerfile
  server/package.json
Labels: DevOps, Back
